### ISSUE TITLE
Weird bonds in the 2beg_m1_cg.pdb

### ISSUE THREAD

**Issue by BartBruininks** [kkorshunova/multichain-martini-go#2]
If you visualize the 2beg_m1_cg.pdb you see weird bonds between the different segments. This might be required for generating the Mapping file, but I do not see where this part is explained. Maybe it could be neater if we except a clean PDB, then create an intermediate PDB which you can send to the server. Not sure, but at least this should be explained somewhere.

**Comment by kkorshunova** [comment]
The bonds you see connecting the different chains were added before running the martinize2 script in order to avoid skips in residue numbering. I am currently working on a thorough documentation/tutorial update, so I will try to include more information about technical details.
